### ISSUE TITLE
Virtual environment in Dockerfile

### ISSUE THREAD

**Issue by hramezani** [pesarkhobeee/WUIChiBashi#2]
I think creating a virtual env in docker container does not make sense.
https://github.com/pesarkhobeee/WUIChiBashi/blob/24593d49ebfd1fff137034bfe152751b0722baec/Dockerfile#L13

Probably you will create a container to run just this project. So, why virtual environment in container?

**Comment by pesarkhobeee** [comment]
Dear @hramezani 
As I mentioned in the resources section of the README file, because I am not an expert in the Python I was following this tutorial:
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xix-deployment-on-docker-containers
As you can see some people asked about this issue there but like him, I can not see any harm to using virtual environment even in the container:
![screenshot from 2019-02-18 20-50-40](https://user-images.githubusercontent.com/147461/52973607-ddd46d80-33be-11e9-8cfb-777db7f139c4.png)

**Comment by hramezani** [comment]
Yes, there is no problem to use the virtual environment in a docker container. but what is the benefit?

**Comment by pesarkhobeee** [comment]
avoiding future mistakes? just imagine one of the developers for any reason decided to use a general docker image like Ubuntu instead of python:3.7-alpine, in that case, this will isolate the program python environment from the OS python environment.
